add radon to backend workflow

diff --git a/.github/workflows/pr_checks_backend.yml b/.github/workflows/pr_checks_backend.yml
--- a/.github/workflows/pr_checks_backend.yml
+++ b/.github/workflows/pr_checks_backend.yml
@@ -8,7 +8,7 @@ on:
       - 'data/**'
       - 'Dockerfile-pg'
       - 'init_pg.sql'
-      - 'docker compose.yml'
+      - 'docker-compose.yml'
   workflow_dispatch:
 
 jobs:
@@ -29,11 +29,43 @@ jobs:
         with:
           python-version: '3.11.4'
 
+      - name: Install Radon
+        run: pip install radon
+
+  run-radon:
+    runs-on: ubuntu-latest
+    needs: setup
+    continue-on-error: true # Ensure workflow continues on error
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Run Radon Maintainability Index (MI) and Halstead Checks
+        run: |
+          # Run Maintainability Index analysis and capture bad grades (below B)
+          bad_grades=$(radon mi -s data/ | grep -E " - [CDEF] \(" || true)
+
+          if [[ ! -z "$bad_grades" ]]; then
+            echo "Bad MI grades found:"
+            echo "$bad_grades"
+          else
+            echo "Radon MI checks passed successfully"
+          fi
+
+          # Run Halstead complexity analysis and check for effort > 2000
+          high_effort=$(radon hal data/ -s | awk '/effort/ { if ($3 > 2000) print $0 }')
+
+          if [[ ! -z "$high_effort" ]]; then
+            echo "High Halstead effort found:"
+            echo "$high_effort"
+          else
+            echo "Halstead checks passed successfully"
+          fi
+
   run-formatter:
     runs-on: ubuntu-latest
     needs: setup
     continue-on-error: true
-
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -47,7 +79,6 @@ jobs:
     runs-on: ubuntu-latest
     needs: setup
     continue-on-error: true
-
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -60,7 +91,6 @@ jobs:
   build-project:
     runs-on: ubuntu-latest
     needs: setup
-
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -73,7 +103,6 @@ jobs:
   run-services:
     runs-on: ubuntu-latest
     needs: build-project
-
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -86,7 +115,6 @@ jobs:
   check-build-status:
     runs-on: ubuntu-latest
     needs: run-services
-
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -103,7 +131,6 @@ jobs:
   check-lint-format-status:
     runs-on: ubuntu-latest
     needs: [run-formatter, run-linter]
-
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
