update pr checks backend to check postgres container and run black formatter

diff --git a/.github/workflows/pr_checks_backend.yml b/.github/workflows/pr_checks_backend.yml
--- a/.github/workflows/pr_checks_backend.yml
+++ b/.github/workflows/pr_checks_backend.yml
@@ -6,6 +6,9 @@ on:
       - staging
     paths:
       - "data/**"
+      - "Dockerfile-pg"
+      - "init_pg.sql"
+      - "docker-compose.yml"
 
 jobs:
   build:
@@ -26,22 +29,51 @@ jobs:
         with:
           python-version: "3.11.4"
 
+      - name: Run Black Formatter in Docker
+        run: |
+          docker-compose run --rm formatter
+        continue-on-error: true
+
+      - name: Run Flake8
+        run: |
+          pip install flake8
+          flake8 data
+        continue-on-error: true
+
       - name: Install dependencies and build Docker images
         run: |
           cd data
           docker-compose pull
           docker-compose build
+
       - name: Run vacant-lots-proj
         run: |
           cd data
           docker-compose up -d vacant-lots-proj
         continue-on-error: true
 
+      - name: Build and check Postgres container
+        run: |
+          cd data
+          docker-compose build postgres
+        continue-on-error: true
+
       - name: Check build status
         if: failure()
         run: |
-          echo "The vacant-lots-proj failed to build and run."
+          echo "The vacant-lots-proj or postgres container failed to build and run."
           exit 1
+
       - name: Report success
         if: success()
-        run: echo "The vacant-lots-proj built and ran successfully."
+        run: echo "The vacant-lots-proj and postgres container built and ran successfully."
+
+      - name: Check formatter and linter status
+        if: failure()
+        run: |
+          echo "Formatting or linting issues found. Please fix the issues."
+          exit 1
+
+      - name: Formatter and linter success
+        if: success()
+        run: echo "Formatting and linting passed successfully."
