chore: integrate semantic release and publish release notes

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,4 +1,4 @@
-name: Release
+name: Publish Release
 
 on:
   push:
@@ -9,29 +9,71 @@ on:
 jobs:
   release:
     runs-on: ubuntu-latest
+
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
       - name: Set up Node.js
         uses: actions/setup-node@v4
         with:
           node-version: '20.8.1'
 
-      - name: List files in the root directory
-        run: ls -al
-
-      - name: Check if package-lock.json exists
-        run: test -f package-lock.json && echo "package-lock.json exists" || echo "package-lock.json does not exist"
-
-      - name: Clear NPM Cache
-        run: npm cache clean --force
-
       - name: Install dependencies
         run: npm ci
 
-      - name: Semantic Release
+      - name: Create Tag
+        uses: cycjimmy/semantic-release-action@v4.1.1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
-        run: npx semantic-release
+
+      - name: Read version number
+        id: get_version
+        run: |
+          set -e
+          # Capture the new version from version.txt
+          if [ -f version.txt ]; then
+            version=$(cat version.txt)
+            echo "version=${version}" >> $GITHUB_OUTPUT
+          else
+            echo "version not found!"
+            exit 1
+          fi
+
+      - name: Publish Release Notes
+        uses: actions/github-script@v6
+        env:
+          NEW_VERSION: ${{ steps.get_version.outputs.version }}
+        with:
+          script: |
+            const newVersion = process.env.NEW_VERSION ? process.env.NEW_VERSION.trim() : "unknown";
+            const tagName = `v${newVersion}`;
+
+            const response = await github.rest.repos.createRelease({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              tag_name: tagName,
+              name: `Version ${newVersion}`,
+              generate_release_notes: true,
+              draft: false,
+              prerelease: false
+            });
+
+            const date = new Date().toLocaleDateString("en-US", {
+              timeZone: "America/New_York",
+              year: "numeric",
+              month: "long",
+              day: "numeric"
+            });
+            const customHeader = `Release Notes for Version ${newVersion} - ${date}\n\n`;
+            const updatedBody = customHeader + response.data.body;
+
+            await github.rest.repos.updateRelease({
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              release_id: response.data.id,
+              body: updatedBody,
+              name: `Version ${newVersion}`
+            });
